[build]
builder = "nixpacks"
buildCommand = "npm run build"
watchPatterns = ["src/**", "package.json", "tsconfig.json"]

[deploy]
startCommand = "npm run start:production"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3